spring:
  datasource:
    url: jdbc:mysql://192.168.220.3:3306/security_authority?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true