spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_authority?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true